/*
 Copyright (c) 2005-2020 Oracle and/or its affiliates. Contains software licensed under the MIT license. Removal of this notice is prohibited. Full attribution and licensing at: http://ccexperimentsstatic.oracleoutsourcing.com/api/license.html 
*/
(function(){var F=window.ATGSvcs||{};if(!F.REC_VERSION){F.CFG||(F.CFG={});var Fb=function(){var a=null,b=function(a,b,c){var d="object"===typeof a?a:{complete:c||!c&&b||M(a)&&a,duration:a,easing:c&&b||b&&!M(b)&&b};d.old=d.complete;d.complete=function(){M(d.old)&&d.old.call(this)};return d},d={linear:function(a,b,c,d){return c+d*a},swing:function(a,b,c,d){return(-Math.cos(a*Math.PI)/2+.5)*d+c}},c=[],e=function(a,b,c){this.options=b;this.elem=a;this.prop=c;b.orig||(b.orig={})},g={opacity:function(a){O(a.elem,
"opacity",a.now)},_default:function(a){a.elem.style&&null!=a.elem.style[a.prop]?a.elem.style[a.prop]=a.now+a.unit:a.elem[a.prop]=a.now}};e.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(g[this.prop]||g._default)(this);"height"!=this.prop&&"width"!=this.prop||!this.elem.style||(this.elem.style.display="block")},cur:function(a){return null==this.elem[this.prop]||this.elem.style&&null!=this.elem.style[this.prop]?(a=parseFloat(O(this.elem,this.prop,a)))&&
-1E4<a?a:parseFloat(O(this.elem,this.prop))||0:this.elem[this.prop]},custom:function(b,d,e){function g(a){return f.step(a)}this.startTime=+new Date;this.start=b;this.end=d;this.unit=e||this.unit||"px";this.now=this.start;this.pos=this.state=0;var f=this;g.elem=this.elem;g()&&c.push(g)&&!a&&(a=setInterval(function(){for(var b=0;b<c.length;b++)c[b]()||c.splice(b--,1);c.length||(clearInterval(a),a=n)},13))},step:function(a){var b=+new Date;if(a||b>=this.options.duration+this.startTime){this.now=this.end;
this.pos=this.state=1;this.update();a=this.options.curAnim[this.prop]=!0;for(var c in this.options.curAnim)!0!==this.options.curAnim[c]&&(a=!1);if(a){null!=this.options.display&&(this.elem.style.overflow=this.options.overflow,this.elem.style.display=this.options.display,"none"==O(this.elem,"display")&&(this.elem.style.display="block"));if(this.options.hide||this.options.show)for(var e in this.options.curAnim)O(this.elem,e,this.options.orig[e]);this.options.complete.call(this.elem)}return!1}c=b-this.startTime;
this.state=c/this.options.duration;this.pos=d[this.options.easing||(d.swing?"swing":"linear")](this.state,c,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update();return!0}};return function(a,c,d,g,m){var f=b(d,g,m);a.length||(a=[a]);return q(a,function(){var a=ua({},f),b,d=this;for(b in c)"height"!=b&&"width"!=b||!this.style||(a.display=O(this,"display"),a.overflow=this.style.overflow);null!=a.overflow&&(this.style.overflow="hidden");a.curAnim=ua({},c);q(c,function(b,
c){var g=new e(d,a,b),f=c.toString().match(/^([+-]=)?([\d+-.]+)(.*)$/),l=g.cur(!0)||0;if(f){c=parseFloat(f[2]);var v=f[3]||"px";"px"!=v&&(d.style[b]=(c||1)+v,l*=(c||1)/g.cur(!0),d.style[b]=l+v);f[1]&&(c=("-="==f[1]?-1:1)*c+l);g.custom(l,c,v)}else g.custom(l,c,"")});return!0})}}(),r={match:function(a){var b=document.cookie.split(/; ?/),d=0;for(6!=z(a)&&(a=J(a));d<b.length;){var c=b[d++].split("=");if(~c[0].search(a)){var e=e||{};e[c[0]]=u(c[1])?decodeURIComponent(c[1]):""}}return e},has:function(a){a=
r.get(a);return!!a||""===a},get:function(a){var b=r.match(6==z(a)?a:"^"+a+"$");if(b)return b[a]||""},set:function(a,b,d){var c="; SameSite=None; path=/",e=location.hostname,g=e.split("."),f=g.length;/^(\d{1,3}\.){3}\d{1,3}$/.test(e)||(e=(size=2<f&&/^(COM|EDU|NET|ORG|GOV|MIL|INT)$/i.test(g[f-1])?-2:3<f?-3:0)?"."+g.slice(size).join("."):1==f?0:e);c+=e?"; domain="+e:"";if(!0===d)var l="Fri, 01 Jan 2038 00:00:00 GMT";else d!==n&&(l=new Date,l.setTime(+l+36E5*d),l=l.toGMTString());l&&(c+="; expires="+
l);"https:"==Gb(1)&&(c+="; Secure");k("Setting Cookie: "+a+"="+va(b)+c);document.cookie=a+"="+va(b)+c}},O=function(){var a=function(a,b,c){var d={},g;for(g in b)d[g]=a.style[g],a.style[g]=b[g];c.call(a);for(g in b)a.style[g]=d[g]},b=/z-?index|font-?weight|opacity|zoom|line-?height/i,d=/opacity=([^)]*)/,c=function(b,c,d,g){if("width"==c||"height"==c){d=function(){f="width"==c?b.offsetWidth:b.offsetHeight;"border"!==g&&q(h,function(){g||(f-=parseFloat(e(b,"padding"+this,!0))||0);f="margin"===g?f+(parseFloat(e(b,
"margin"+this,!0))||0):f-(parseFloat(e(b,"border"+this+"Width",!0))||0)})};var f,l={position:"absolute",visibility:"hidden",display:"block"},h="width"==c?["Left","Right"]:["Top","Bottom"];0!==b.offsetWidth?d():a(b,l,d);return Math.max(0,Math.round(f))}return e(b,c,d)},e=function(a,b,c){l||m();var g=a.style;if("opacity"==b&&!E.opacity&&a.currentStyle){var e=d.test(a.currentStyle.filter||"")?parseFloat(RegExp.$1)/100+"":"";return""==e?"1":e}b.match(/float/i)&&(b=h.styleFloat);!c&&g&&g[b]?e=g[b]:Hb.getComputedStyle?
(b.match(/float/i)&&(b="float"),b=b.replace(/([A-Z])/g,"-$1").toLowerCase(),(a=Hb.getComputedStyle(a,null))&&(e=a.getPropertyValue(b)),"opacity"==b&&""==e&&(e="1")):a.currentStyle&&(e=b.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()}),e=a.currentStyle[b]||a.currentStyle[e],!/^\d+(px)?$/i.test(e)&&/^\d/.test(e)&&(b=g.left,c=a.runtimeStyle.left,a.runtimeStyle.left=a.currentStyle.left,g.left=e||0,e=g.pixelLeft+"px",g.left=b,a.runtimeStyle.left=c));return e},g=function(a,c,d){var g=c,e;if(("width"==
c||"height"==c)&&0>parseFloat(d))return a;"string"===typeof c&&(g={},g[c]=d);for(e in g)g.hasOwnProperty(e)&&(d=g[e],"number"!==typeof d||b.test(e)||(d+="px"),f(a.style,e,d));return a},f=function(a,b,c){l||m();b=h[b]||b;E.opacity||"opacity"!=b?(b=b.replace(/-([a-z])/ig,function(a,b){return b.toUpperCase()}),a[b]=c):(a.zoom=1,a.filter=(a.filter||"").replace(/alpha\([^)]*\)/,"")+("NaN"==parseInt(c)+""?"":"alpha(opacity="+100*c+")"))},l=!1,E={},h={},m=function(){if(!l){var a=document.createElement("div");
a.style.display="none";a.innerHTML='<a href="/a" style="float:left;opacity:.5;">a</a>';a=a.getElementsByTagName("a")[0];var b=a.style.cssFloat?"cssFloat":"styleFloat";E={opacity:"0.5"===a.style.opacity,cssFloat:!!a.style.cssFloat};h["float"]=b;h.cssFloat=b;h.styleFloat=b;l=!0}};window.setTimeout(m,0);return function(){return"object"===typeof arguments[1]||arguments[2]!==n&&"boolean"!==typeof arguments[2]?g.apply(this,arguments):c.apply(this,arguments)}}(),Ga=[],k=function(){window.console&&window.console.log&&
console.log([].slice.call(arguments))},qc=k,K={create:function(a,b){a=document.createElement(a);var d=b[0]||{},c=1,e,g;b[0]&&(b[0].constructor!=Object||b[0].tagName)&&(d={},c=0);for(e in d)switch(e){case "Class":case "class":a.className=d[e];break;case "style":a.style.cssText=d[e];break;default:a[e]=d[e]}for(;c<b.length;c++)if(e=b[c])for(e.constructor!=Array&&(e=[e]),d=0;d<e.length;d++)if(g=e[d]){if("number"==typeof g||"string"==typeof g)g=document.createTextNode(""+g);try{a.appendChild(g)}catch(f){k(f,
g)}}return a},tag:function(a){a&&!K[a]&&(K[a]=function(){return K.create(a,arguments)})},tags:function(a){a=a.split(/\|/);for(var b=0;b<a.length;b++)K.tag(a[b])}},ab=[],wa=function(a,b,d,c){ab.push([a,b,d,c]);Ib(a,b,d,c)},Ib=function(a,b,d,c){var e=(c||"")+b+d;a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent&&(a["e"+e]=d,a[e]=function(){a["e"+e](window.event)},a.attachEvent("on"+b,a[e]))},bb=function(a,b,d,c){c=(c||"")+b+d;a.removeEventListener?a.removeEventListener(b,d,!1):a.detachEvent&&
(a.detachEvent("on"+b,a[c]),a[c]=a["e"+c]=null)},t={E:{},W:[],B:{},occur:function(a){a=[].concat(a);for(var b=0,d=0;b<a.length;){var c=a[b++],e=1<arguments.length?[].slice.call(arguments,1):[];k("eventOccur called with event "+c+" and args ",e);var g=t.E,f=t.W,l=t.B[c]||[],E=l.length,h,m={type:c,ergCount:g[c],ergStamp:+new Date};g[c]=g[c]?g[c]+1:1;for(h=0;h<f.length;){var v=f[h][0];var x=f[h][1];t.gate(v)?(f.splice(h,1),x[0].apply(v,x[1])):h++}for(;E--;)m.data=l[E][1],l[E][0].apply(null,[m].concat(e));
d+=g[c]}return d},gate:function(a){var b=t.E,d;for(d in a)if(a.hasOwnProperty(d)&&(!0===a[d]?!b[d]:!(0<b[d]-a[d])))return!1;return!0},cond:function(a,b){var d=t.E;return b&&!0!==b?0<d[a]-b:d[a]},wait:function(a,b){t.W.push([a,[b,[].slice.call(arguments,2)]])},bind:function(a,b,d){var c=!1;d=d||{};a=t.B[a]=t.B[a]||[];for(var e=a.length;e--;)c=c||a[e][0]===b;c||a.push([b,d])},unbind:function(a,b){for(var d=t.B[a]||[],c=d.length;c--;)d[c][0]===b&&d.splice(c,1);d.length||delete t.B[a]}},cb=function(a){ba(a)?
q(a,function(a,d){M(d)&&t.bind(a,d)}):k("ERROR: eventSubscribe requires an object as a parameter")},xa=function(){var a=Array.prototype.slice,b=document.createElement("div"),d={};try{a.call(b.childNodes)}catch(C){a=function(a){for(var b=[],c=this.length;a<c;)b[a]=this[a++];return b}}if(b.querySelectorAll)return b=null,function(b,c){return a.call((c||document).querySelectorAll(b),0)};b.className="x";b.getAttribute("className")&&(d={"class":"className"});var c=/^#[a-zA-Z0-9_\-]+$/,e=/^(\*|[a-zA-Z0-9]+)$/,
g=/^\.[a-zA-Z0-9_\-]+$/,f=/^(\*|[a-zA-Z0-9]+)\.[a-zA-Z0-9_\-]+$/,l=/^(\*|[a-zA-Z0-9]+)\[(.+)\]+$/,E=/[^>|\+|\-|\*|~|\]|\w]*(>|\s)+(?!\+|\-|\*|~)/,h=function(b,d,q){b=b.replace(/^\s+|\s+$/g,"");var C=b.match(E),w=[],I=[],ha;if(C){C=C[0];var Ha=b.indexOf(C);var n=b.substr(0,Ha)}else n=b;c.test(n)?(n=m(n.substring(1),d))&&w.push(n):e.test(n)?w.push.apply(w,a.call(d.getElementsByTagName(n),0)):g.test(n)?w.push.apply(w,v(n.substring(1),d)):f.test(n)?w.push.apply(w,x(n,d)):(ha=n.match(l))&&w.push.apply(w,
k(ha[1],ha[2],d));if(Ha)for(ha=w.length,n=b.substr(Ha+C.length);ha;)I=I.concat(h(n,w[--ha],~C.indexOf(">")));else I=w;if(Ha||q)I=p(I,q?d:"");return I},m=b.all?function(a,b){for(var c=b=b.all[a],d=0;c;){if(c.id==a)return c;c=b[d++]}return null}:function(a,b){return"undefined"!==typeof b.getElementById?b.getElementById(a):(a=document.getElementById(a))?a.compareDocumentPosition(b)&8?a:null:null},v=b.getElementsByClassName?function(b,c){return a.call(c.getElementsByClassName(b),0)}:function(a,b){return x("*."+
a,b)},x=function(a,b){a=a.split(".");for(var c=b.getElementsByTagName(a.shift()),d=new RegExp("(?:\\s|^)"+a.shift()+"(?:\\s|$)"),g=c.length,e=0,f=0;e<g;++e)b=c[e],d.test(b.className)&&(a[f++]=b);return a},k=function(a,b,c){a=c.getElementsByTagName(a);var g=b.match(/([^~\|=]*)(~|\|)*=*(.*)/);b=a.length;c=[];var e=g[1],f=g[2];g=g[3];var l;g=f?"~|".indexOf(f)?"^"+g+"-*":"(?:\\s|^)"+g+"(?:\\s|$)":"^"+(g||".*")+"$";for(e=d[e]||e;b;)f=a[--b],(l=f.getAttribute(e,0))&&~l.search(g)&&c.push(f);return c},p=
b.uniqueID?function(a,b){for(var c=[],d={},g=a.length,e=0,f;g;)f=a[--g],d[f.uniqueID]||b&&f.parentNode!=b||(c[e++]=f,d[f.uniqueID]=1);return c}:function(a,b){for(var c=[],d=a.length,g=0,e=0,f;g<d;g++)f=a[g],f[975864012]||b&&f.parentNode!=b||(c[e++]=f,f[975864012]=1);for(g=0;g<e;g++)delete c[g][975864012];return c};b=null;return function(a,b){b=b||document;a=a.split(/\s*,\s*/);for(var c=a.length,d=[];c;)d=d.concat(h(a[--c],b));return d}}(),db=Object.prototype.toString,eb=navigator.userAgent.toLowerCase(),
va=window.encodeURIComponent,n,Jb=eb.match(/msie (\d+)/)?+RegExp.$1:0,rc=eb.match(/ (edge\/|trident.*rv:)(\d+)/)?+RegExp.$2:Jb,J=function(a){return(a||"").replace(/^\s+|\s+$/g,"")},M=function(a){return"[object Function]"===db.call(a)},D=function(a){return"[object Array]"===db.call(a)},Hb=document.defaultView||{},q=function(a,b,d){var c,e=0,g=a.length;if(d)if(g===n)for(c in a){if(a.hasOwnProperty(c)&&!1===b.apply(a[c],d))break}else for(;e<g&&!1!==b.apply(a[e++],d););else if(g===n)for(c in a){if(a.hasOwnProperty(c)&&
!1===b.call(a[c],c,a[c]))break}else for(d=a[0];e<g&&!1!==b.call(d,e,d);d=a[++e]);return a},ua=function(){var a=arguments[0]||{},b=1,d=arguments.length,c=!1,e;"boolean"===typeof a&&(c=a,a=arguments[1]||{},b=2);"object"===typeof a||M(a)||(a={});d==b&&(a=p,--b);for(;b<d;b++)if(null!=(e=arguments[b]))for(var g in e){var f=a[g],l=e[g];a!==l&&(c&&l&&"object"===typeof l&&!l.nodeType?a[g]=ua(c,f||(null!=l.length?[]:{}),l):l!==n&&(a[g]=l))}return a},fb=/gomezagent/.test(eb),Kb=function(a,b){if(!a||"object"!=
typeof a)return a;var d=a.constructor===Array?[]:{};q(a,function(a,e){isNaN(a)&&b&&"-"==a.charAt(0)||(d[a]=Kb(e,b))});return d},gb=function(a,b,d,c){var e=[],g,f=6==z(a),l=f?"r":c.compare||"=";"="==l&&(/^("|').*\1$/.test(a)&&(a=a.slice(1,-1)),"id"==d&&(a=a.replace(/^#/,"")));q(xa(b),function(b,h){g=h.getAttribute(d)||"";c.trim&&(g=J(g));f||c["case"]||(g=S(g));ia(g,a,l)&&e.push(h)});return e},Lb=function(){var a=arguments,b=a.length,d,c=0;if(1==b)var e=a[0];else for(e={};c<b;)(d=a[c++])&&(e[d]=a[c++]);
e&&ua(!0,p.CFG,e)},Mb=function(a,b){return a.replace(/^([^/:]*:?\/\/)*([^\/]+[^\.])\//,function(a,c,e){return(b?"https:":document.location.protocol)+"//"+e+"/"})},Nb=function(a,b){return(b&&2!==b?y("-exp-host","ccrules.oracleoutsourcing.com"):y("-rules-host","rules.atgsvcs.com"))+"/"+y("-rules-base-path","EERules/")+a+"/3.0/json/"+(b?A:B)},sc=function(a){return Ia(a,2)},Ob=function(a){return Ia(a,1)},Ia=function(a,b){var d=V?P:L(),c=V?T:hb();return Nb(a,b)+(d?"/"+d:"")+(c?"?sessionId="+c+"&E3SessionID="+
c:"")},Ja=function(a,b){var d,c=[],e;b=b?b+".":"";q(a,function(a,f){if(null!=f){e=b+a;if(D(f))if((d=f.length)&&ba(f[0]))f=Ja(tc(f),e);else{for(;d--;)f[d]=va(f[d].replace(/(,|\\)/g,"\\$1"));f=e+"="+f.join(",")}else f=ba(f)?Ja(f,e):e+"="+va(""+f);f&&c.push(f)}});return c.join("&")},tc=function(a){k("convert ArrayOfHashes to HashOfParallelLists",a);var b={},d,c,e=a.length;e&&(q(a,function(a,c){q(c,function(a){b[a]=[]})}),q(b,function(b,f){for(d=0;d<e;d++)c=a[d][b],f.push(c==n?"":""+c)}));return b},ib=
function(a,b,d){a=Mb(a,d);b&&(a+=(~a.indexOf("?")?"&":"?")+Ja(b));2048<a.length&&k("WARNING: URL is over 2048 Bytes and will be truncated in IE !!!");return a},ca=function(a,b,d){a=ib(a,b);d=K.SCRIPT({charset:y("charset","utf-8"),src:d?a.replace(/^http:/i,"https:"):a});k("Sending Request: "+d.src);Pb(d)},ja=function(a,b){return"https://"+(b?y("-exp-static-host","ccexperimentsstatic.oracleoutsourcing.com"):y("-static-host","ccexperimentsstatic.oracleoutsourcing.com"))+"/"+a},Ka=function(a,b){var d=
[],c=[],e=function(){var a={};q(p.CFG,function(b,c){"object"!=typeof c&&(a[b]=c)});return a}(),g=function(a){var b=0,d;if(a)try{for(;b<c.length;b++)if(d=a[c[b][1]])c[b][0](d)}catch(h){A&&Q(h,"callback",2,n,1)}};this.addResource=function(a,b){jb(a,d)||d.push(a);ua(!0,e,b);t.occur(a)};this.addCallback=function(a,b){c.push([a,b])};this.send=function(b){var c=Mb(a(d.join("/")),b),f="application/x-www-form-urlencoded";b=y("charset","utf-8");var h=window,m=h.JSON,v,x=this;f=Kb(e,1);f.uoid=this.exp?A:B;
if(h.XMLHttpRequest&&m&&m.stringify&&m.parse&&!rc){var w=new XMLHttpRequest;if("withCredentials"in w){h=h.Prototype&&M(Object.toJSON)?Object.toJSON(f):m.stringify(f);k("Sending Request via XHR:",c,f);w.open("POST",c,!0);f=y("-rules-content-type","application/x-www-form-urlencoded");"application/x-www-form-urlencoded"==f&&(h=va(h));var q=W(y("-eeTimeout"));q&&(w.exp=this.exp,w.timeout=q,w.trackedRequestURL=c,w.ontimeout=function(){this.exp?(X=[],da={},Qb(-1)):Y=[];ka();k((this.exp?"Exp":"EE")+" Request "+
this.trackedRequestURL+" timed out after "+this.timeout+"ms")});w.onreadystatechange=function(){v=J(this.responseText);if(4==this.readyState&&200==this.status&&v)try{g(m.parse(v))}catch(C){Q(C,"callback",2,n,x.exp),k("  Request error with "+c+" :"+C.name+", message:"+C.message)}};w.withCredentials=!0;w.setRequestHeader("Content-Type",f+";charset="+b);w.send(h);return}}f.callback=uc(g);ca(c,f)};1===b?this.exp=1:this.addCallback(Rb,"tracking")},Sb,ya,kb,La,H,Tb,Vb=function(){if(!za&&Ma()&&T&&!Tb){var a=
window._eeq;window._eeq=Ub;Tb=1;D(a)&&q(a,function(a,d){Ub.push(d)})}},Wb=function(){H=window.OracleUnifiedVisit;if(V&&!kb&&H&&H.VERSION){var a=H.accountId,b=y("-sf-eeid")||H.eeid||(window._ATGSvcs||{}).eeid;if(a&&!A){Aa(a);var d=1}B&&!A&&(Aa(B),d=1);b&&(la(b),d=1);A&&B&&0==A.indexOf(B)&&(A=B);B==A&&(la(),Aa(A));d&&(y("-exp-host")||(p.CFG["-exp-host"]=y("-rules-host")),y("-exp-static-host")||(p.CFG["-exp-static-host"]=y("-static-host")));a=Ma();d=lb();a&&d&&(mb(a),r.set(ma,a,!0),T=d);Vb();kb=1}},
oa=function(){if(!Na&&(Wb(),kb)){Na=1;k("Starting initialization...");t.occur("ready");var a=p.setupFn||F.setupFn;if(M(a))try{a()}catch(b){Q(b,"setup",2)}V?Ba(P)||!B&&!A||Oa():Ba(P)&&B?Sb||(Sb=1,ca(Nb("xd")+"/xd.js",n,na())):(L()||L(P),Oa());!fb&&B&&t.occur(["estara_ready","webcare_ready"]);A&&za&&(window.eeExp&&window.eeExp.js?ca(ja(window.eeExp.js,1),n,1):ca(ja("js/eeExp.js",1),n,1));k("Initialization complete...")}},$b=function(){if(B&&!r.has(nb)&&!ob){ob=1;k("Request rules data");var a=new Ka(Ia);
t.occur(["plato_ready","eeReady"]);a.addResource("view",{view:{referrer:document.referrer||n,pageTitle:document.title||n}});a.addResource("rules",{rules:{estaraFsGuid:pb(),locHash:location.hash||n,spa:y("-eeSPA")||V?1:n,debug:r.get(Xb),ip:r.get(Yb)}});a.addCallback(qb,"donotcall");a.addCallback(rb,"configuration");a.addCallback(Zb,"invites");a.addCallback(sb,"ab");a.addCallback(tb,"rules");a.send(na())}},Oa=function(){if(Na&&!ya&&(ya=1,!fb&&($b(),A))){k("Request experiment data");var a=new Ka(Ob,
1);t.occur("expReady");a.addResource("view",{view:{referrer:document.referrer||n,pageTitle:document.title||n}});a.addResource("rules",{rules:{locHash:location.hash||n,noExperiments:za,spa:""+document.location}});a.addCallback(ac,"configuration");a.addCallback(bc,"ab");a.addCallback(cc,"topics");a.addCallback(dc,"rules");a.send(na())}},Na=!1,vc=function(){document.addEventListener?document.addEventListener("DOMContentLoaded",function(){document.removeEventListener("DOMContentLoaded",arguments.callee,
!1);oa()},!1):document.attachEvent&&"complete"!=document.readyState&&(document.attachEvent("onreadystatechange",function(){"complete"==document.readyState&&(document.detachEvent("onreadystatechange",arguments.callee),oa())}),document.documentElement.doScroll&&window==window.top&&function(){if(!Na){try{document.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}oa()}}());Ib(window,"load",oa)},ma="atgRecVisitorId",nb="atgPlatoStop",Ba=function(a){return!a||a==""+n||/^-?\d+$/.test(a)},
ec=function(){var a=(r.get("xdVisitorId")||"").replace(/!\d+$/,"");if(a!=""+n)return a},L=function(a){a&&(r.set(ma,a,!0),fc=a);return P||r.get(ma)||fc},hb=function(a){a&&(r.set("atgRecSessionId",a),gc=a);return r.get("atgRecSessionId")||gc},ub=function(){if(La||0===La){var a=ec()||""+n;r.set("xdVisitorId",a.replace(/(!\d+)?$/,"!"+La),!0)}},mb=function(a){P=Ma()||ec();a&&(a.donotcall&&qb(),Ba(P)&&((P=a.visitorId)?Rb(a):(P=a)&&L(a)));Ba(P)||Oa();ub()},Rb=function(a){k("Setting tracking values:"+(a&&
a.visitorId?" visitorId:"+a.visitorId:"")+(a&&a.sessionId?" sessionId:"+a.sessionId:""));a&&(a.visitorId&&L(a.visitorId),a.sessionId&&hb(a.sessionId));t.occur("tracking")},Pa,Qa,bc=function(a){Qa=a;sb(a,1)},sb=function(a,b){k("Initialize AB test data");b=1===b;if(D(a)){b||(Pa=a);var d={};q(a,function(a,e){q(e.goals||[],function(a,c){/^ee[A-Z]/.test(c.name)||(c.val=c.name,c.name="eeCustomEvent");d[c.name]=b?wc:Ra})});delete d.eeAbStart;cb(d)}},xc=function(a){var b=a.id;pa((a.exp?Qa:Pa)||[],function(d){d.id==
b&&(d.started=1,Ra({type:"eeAbStart"},{type:a.type,a:b,exp:a.exp}))})},wc=function(a,b){b.exp=1;Ra(a,b)},Ra=function(a,b){b=b||{};var d=a.type;/Offer|Accept/.test(d)&&!/On$/.test(b.link&&b.link.logStatus||"")||q(b.exp?Qa:Pa,function(a,e){!e.started||b.a&&b.a!=e.id||q(e.goals||[],function(a,c){d!=c.name||c.w&&c.w!=(b.id||b.linkid)||c.r&&c.r!=(b.rule&&b.rule.id)||c.val&&c.val!=b.data&&"eeCustomEvent"==d||(a={id:e.id,g:c.id,customVars:Sa()},b.a&&(a.type=b.type),R("abEvent",{ab:a},b.exp))})})},hc={},
cc=function(a){D(a)&&window.$&&$.Topic&&q(a,function(a,d){var b=d&&d.topicName;b&&!hc[b]&&($.Topic(b).subscribe(function(){d.expGoalIds&&d.expGoalIds.length&&q(d.expGoalIds,function(a,c){R("ccEvent",{t:"4",g:c.goalId,e:c.expId,d:[{n:"topic",v:b},{n:"topicId",v:d.topicId}],c:"NONE"},1)})}),hc[b]=1)})},wb=function(){var a,b={fade:function(a){var c=p.rules.faders,d=a.s+a.select;c[d]=c[d]||[];c[d].push(setTimeout(function(){a.d=a.d||a.h;var g=Ca(a);!g||(c[d]||[]).length&&.1>O(g,"opacity")||Fb([g],{opacity:0},
a.t||0,n,function(){a.j&&Z(a.j,"()");a.h&&b.showHide(a)})},a.d));p.rules.faders=c},displayPagePeek:function(a,b){N.enabled&&!N.active&&(N.active=1,N.host=Gb(1)+("//"+(p.ESTARA_HOST||F.ESTARA_HOST||"as00.estara.com")),a=function(){var a=p,b=a.cobrowse;a.pagepeek.launch=1;b&&M(b.uploadPP)&&b.uploadPP()},t.cond("eeAccepted")?a():t.wait({eeAccepted:!0},a),ca(ja("js/pp.js")))},runJavaScript:function(a,b){Z(a.callBack,"()")},loadJavaScript:function(a,b){a.url&&ca(a.url,n,na()||/^https:/i.test(a.url))},
loadLegacyRules:yc,rnSynProactiveChat:function(a,b){var c=a.rnJSON||{};c.type=2;a.divId=c.div_id=c.div_id||"myDiv";qa("ProactiveChat",c,b,a)},rnSynConditionalChatLink:function(a,b){var c=a.rnJSON||{};c.type=7;c.info_element_id=c.info_element_id||"myChatLinkInfo";c.link_element_id=c.link_element_id||"myChatLink";c.container_element_id=c.container_element_id||"myChatLinkContainer";a.divId=[c.info_element_id,c.link_element_id,c.container_element_id];qa("ConditionalChatLink",c,b,a)},rnSynKnowledgeSyndication:function(a,
b){var c=a.rnJSON||{};c.type=3;a.divId=c.div_id=c.div_id||"myDiv";qa("KnowledgeSyndication",c,b,a)},rnSynPollingSyndication:function(a,b){var c=a.rnJSON||{};W(c.survey_id)?(c.type=5,a.divId=c.div_id=c.div_id||"myDiv",qa("PollingSyndication",c,b,a)):k("ERROR: missing survey_id")},rnCPProactiveChat:function(a,b){qa("ProactiveChat",a,b,a)},rnCPConditionalChatLink:function(a,b){qa("ConditionalChatLink",a,b,a)},showLink:function(){},stopProcessingRules:function(a,b){ra.clearAll();p.rules.page.stopProcessing=
1},paramToJavaScriptVar:function(a,b){(b=ic(a.select))&&Z(a.value,"=",b)},populateCustomDataSegment:function(a,b){a:{var c=a.select;for(var d=(location.pathname+"//"+location.hash.slice(1)).split("/"),e=0,E=d.length;e<E;e++)if(ia(d[e],c,"=")){c=d[e+1]||n;break a}c=void 0}c&&ea(a,c,b)},populateCustomDataURL:function(a,b){var c=ic(a.select);c&&ea(a,c,b)},populateCustomDataElementID:function(a,b){var c=Ta(a.select,1,1);c&&ea(a,c,b)},populateCustomDataElementName:function(a,b){var c=Ta(a.select,1);c&&
ea(a,c,b)},populateCustomDataPage:function(a,b){var c=document.body;c=(c?c.innerHTML:"").match(U(a.select,a));var d=+a.multiResItem||0;c&&d<c.length&&ea(a,c[d],b)},populateCustomDataVar:function(a,b){var c=Z(a.select);D(c)&&(c=1<=c.length?c[0]:null);ea(a,c,b)},populateCustomDataValue:function(a,b){ea(a,a.select,b)},hideInformationElementID:function(a,b){N.rules.push([a,"hide","id"])},hideInformationElementName:function(a,b){N.rules.push([a,"hide","name"])},maskInformationElementID:function(a,b){N.rules.push([a,
"mask","id"])},maskInformationElementName:function(a,b){N.rules.push([a,"mask","name"])},chgClass:function(a){var b=Ca(a),c=J(a.c.replace(/ +/g," "));if(b){if("="==a.a)var d=c;else d=" "+(b.className||"").replace(/ +/g," ")+" ",q(c.split(" "),function(a,b){d=d.replace(" "+b+" "," ")}),"+"==a.a&&(d+=" "+c);b.className=J(d.replace(/ +/g," "))}},replaceA:function(b,d){var c=Ca(b);c?q(b.value||{},function(a,b){"label"==a?c.innerHTML=b:"style"==a?c[a].cssText=b:("class"==a&&(a="className"),c[a]=b,c.setAttribute(a,
b))}):a=d&&d.exp},replace:function(c,d){var e=Ca(c),f=c.c||"",l=c.p;if(e){var k=e.outerHTML;if("r"==c.t)"O"==l?k&&(e.outerHTML=f):e.innerHTML="I"==l?f:e.innerHTML.replace(U(c.m),f);else if("W"==l){if(k){if(c.e){var h=K[c.e](c.value);h.innerHTML=k;h=h.outerHTML}else h=f+k+(c.ca||"");e.outerHTML=h}}else if(/[AB]/.test(l))h=K.SPAN(),h.innerHTML=f,e.parentNode.insertBefore(h,/A/.test(l)?e.nextSibling:e),"AB"==l&&(c.p="B",b.replace(c,d));else try{"S"==l&&(h="afterbegin"),"E"==l&&(h="beforeend"),h&&e.insertAdjacentHTML(h,
f)}catch(m){}}else a=d&&d.exp},showHide:function(b,d){var c=Ca(b);c?b.d?O(c,{display:"none",visibility:"hidden"}):O(c,{display:"",visibility:"visible"}):a=d&&d.exp},logCustomEvent:function(a,b){var c=Sa(),d="",e={};a=a.value;var k="TransactionCompleted"==a,h=k?a:"CustomEvent",m={customVars:c,data:a,rule:b};vb("ee"+h,m);Ua(S(h.charAt(0))+h.slice(1),m);if(B&&k){k={accountid:B,eventtype:a.slice(0,-1)};for(h=10;h;--h)k["var"+h]=c["var"+h];h=K.IMG({src:ib("//"+(p.ESTARA_HOST||F.ESTARA_HOST||"as00.estara.com")+
"/webcare/webevents/webevent.php",k,1)})}q(c,function(a,b){u(b)&&(d+=a+":"+b+"&zwnj;#")});e[a]=d?{data:d}:{};R("events",{events:e},b&&b.exp)},urlRedirect:function(a,b){a.url&&(document.location=a.url)},suppressedShowLink:function(){}},d=function(a,d,g){var c=g&&g.exp;if(!c&&G&&1!=G&&G!=location.href)k("skipped running action "+a+" for rule "+g.id+" for "+G+" as we are on "+location.href);else if(b[a])b[a](d.args,g);else"abStart"==a?(c&&(d.exp=1),xc(d)):"abGoal"==a&&Ra({type:d.type},{rule:g,exp:c})};
return{runActions:function(b,e){var c,f;try{q(b,function(b,g){f=b;a=0;c=g.name;k("Run action "+c);d(c,g,e);a&&p.rules.retryActions.push({action:g,context:e})})}catch(l){l.message+=" ["+c+"/"+f+"]",k("ERROR when running actions:"+l.name+", message:"+l.message),Q(l,"action",3,e,e&&e.exp)}},retryActions:function(){var b,e=0,g,f=[],l,E=p.rules;try{q(E.retryActions,function(c,m){l=m.context;g=m.action;e=c;a=0;b=g.name;k("Retry action "+b);d(b,g,l);a&&f.push(m)}),E.retryActions=f}catch(h){E.retryActions.splice(e,
1),h.message+=" ["+b+"/"+e+"]",k("ERROR when rerunning actions:"+h.name+", message:"+h.message),Q(h,"action",3,l,l&&l.exp)}}}}(),zc=function(){var a;return{launch:function(b){ba(b)?(a=b["poll-delay"],(a=u(a)?W(a):-1)&&cb(b)):k("ERROR: analytics.launch requires an object as a parameter")},pollDelay:a}}(),Da,Ub={push:function(a){a=a||{};var b=a.type||a.t,d=a.data||{};switch(b){case -1:d.currencyCode&&(Da=d.currencyCode,k("track _eeq currencySet",Da));break;case 1:Da&&(R("ccEvent",{t:b,d:d,c:Da},1),
k("log _eeq cartAdd",d,Da));break;case 2:d.data&&d.currencyCode&&(R("ccEvent",{t:b,d:d.data,c:d.currencyCode},1),k("log _eeq checkout",d.data,d.currencyCode));break;case 3:if(a.id&&a.v){R("expEvent",{t:b,id:a.id,v:a.v,h:location.hash||n},1);if((b=a.pcm)||0===b)La=b,ub();r.set("eeA"+A,L()+":"+(a.a||""),a.a?744:-1)}break;default:k("Error: unknown data type:",b)}}},Bc=function(){var a="n2 i2 v2 nk ik vk n9 i9 p9 r9 v9 nr ir pr rr vr n8 i8 p8 r8 v8 n6 i6 p7 r7 v6 no io pp rp vo n21 i21 v21 nk1 ik1 vk1 n01 i01 v01 n11 i11 v11 n31 i31 v31 n41 i41 v41 n61 i61 v61 no1 io1 vo1 n8 i8 v8 n22 i22 v22 nk2 ik2 vk2 n32 i32 v32 n02 i02 v02 n52 i52 v52 nn2 in2 vn2 v23 va3 n21i n20f n20d i21i i20f i20d nk1i nk0f nk0d ik1i ik0f ik0d n90f n90d i90f i90d nrif nr0d ir0f ir0d n61i n60f n60d i61i i60f i60d no1i no0f no0d io1i io0f io0d n01i n01f n01d i01i i01f i01d n11i n11f n11d i11i i11f i11d n31i n31f n31d i31i i31f i31d n41i n41f n41d i41i i41f i41d n80i n80f n80d i80i i80f i80d n23c i23c nk3c ik3c vc2 vb2 ve2 vd2 v23 t21 tk1 t31 t01 t41 t11 N23A N23 Na3 N9 Nr N83 N6 No V2 Vk V9 Vr V8 V6 Vo V21 Vk1 V31 V41 V01 V11 V8 I23 I23 I23 I23 I23 I23 I23 I23 I23 I23 L23 L23l v2".split(" "),
b=function(a,b,d,f){var c=d.split(""),e=c[0];d=parseInt(c[1],36);b=17<d;d="< <= = > >= bt in pin r ~ ! +< +> -< ->".split(" ")[b?d-18:d];var g=+c[2]||0;c=c[3]||null;f=a.value;e=a.s||e;g=u(a.f)?a.f:g;a.o&&(b=/!/.test(a.o),d=a.o.replace("!",""));var m=Ac(e,g,a,d,c,b);if(3==g||"L"==e)f=!0;"N"==e&&(/in/.test(d)&&(f=m,m=a.value),"r"==d&&(d="="));if(!u(m)||!u(f)||!u(d))return"";1==g&&(c=Va(m),m=a.p,1==z(c)?(m=Math.pow(10,m||0),m=W(c*m)/m):m=void 0);if("r"==e)return c=m,null==f&&"~"==d&&(f=""),D(f)||(f=
[f]),"r"==d&&(f=Wa(f,U,a)),a=jc(c,f,d,a),b?!a:a;if(2==g)if(/[+-]/.test(d)&&(/-/.test(d)&&(f=-f),d=d.slice(1),c=m,e=Ea,g=new Date,Xa(g)?(g.setDate(g.getDate()+W(f)),f=g):f=null,m=e(f),f=c),"bt"==d){if(!D(f)||2!=f.length)return!1;f=Ya(f,2)}else f=Ea(f);"r"==d&&(f=U(f,a));return ia(m,f,d,b)},d={matchTextEQElementName:0,matchTextEQElementID:1,matchTextEQVar:2,matchTextNEQElementName:3,matchTextNEQElementID:4,matchTextNEQVar:5,matchTextContainsElementName:6,matchTextContainsElementID:7,matchTextContainsPage:8,
matchRendTextContainsPage:9,matchTextContainsVar:10,matchTextNContainsElementName:11,matchTextNContainsElementID:12,matchTextNContainsPage:13,matchRendTextNContainsPage:14,matchTextNContainsVar:15,matchTextRegElementName:16,matchTextRegElementID:17,matchTextRegPage:18,matchRendTextRegPage:19,matchTextRegVar:20,matchTextInElementName:21,matchTextInElementID:22,matchTextInPage:23,matchRendTextInPage:24,matchTextInVar:25,matchTextNInElementName:26,matchTextNInElementID:27,matchTextNInPage:28,matchRendTextNInPage:29,
matchTextNInVar:30,matchNumEQElementName:31,matchNumEQElementID:32,matchNumEQVar:33,matchNumNEQElementName:34,matchNumNEQElementID:35,matchNumNEQVar:36,matchNumLTElementName:37,matchNumLTElementID:38,matchNumLTVar:39,matchNumLTEQElementName:40,matchNumLTEQElementID:41,matchNumLTEQVar:42,matchNumGTElementName:43,matchNumGTElementID:44,matchNumGTVar:45,matchNumGTEQElementName:46,matchNumGTEQElementID:47,matchNumGTEQVar:48,matchNumInElementName:49,matchNumInElementID:50,matchNumInVar:51,matchNumNInElementName:52,
matchNumNInElementID:53,matchNumNInVar:54,matchNumRegElementName:55,matchNumRegElementID:56,matchNumRegVar:57,matchDateEQElementName:58,matchDateEQElementID:59,matchDateEQVar:60,matchDateNEQElementName:61,matchDateNEQElementID:62,matchDateNEQVar:63,matchDateAfterElementName:64,matchDateAfterElementID:65,matchDateAfterVar:66,matchDateBeforeElementName:67,matchDateBeforeElementID:68,matchDateBeforeVar:69,matchDateBetweenElementName:70,matchDateBetweenElementID:71,matchDateBetweenVar:72,matchDateNBetweenElementName:73,
matchDateNBetweenElementID:74,matchDateNBetweenVar:75,matchBooleanTVar:76,matchBooleanFVar:77,matchDropDownEQElementName:78,matchDropDownFormEQElementName:79,matchDropDownDisplayEQElementName:80,matchDropDownEQElementID:81,matchDropDownFormEQElementID:82,matchDropDownDisplayEQElementID:83,matchDropDownNEQElementName:84,matchDropDownFormNEQElementName:85,matchDropDownDisplayNEQElementName:86,matchDropDownNEQElementID:87,matchDropDownFormNEQElementID:88,matchDropDownDisplayNEQElementID:89,matchDropDownFormContainsElementName:90,
matchDropDownDisplayContainsElementName:91,matchDropDownFormContainsElementID:92,matchDropDownDisplayContainsElementID:93,matchDropDownFormNContainsElementName:94,matchDropDownDisplayNContainsElementName:95,matchDropDownFormNContainsElementID:96,matchDropDownDisplayNContainsElementID:97,matchDropDownInElementName:98,matchDropDownFormInElementName:99,matchDropDownDisplayInElementName:100,matchDropDownInElementID:101,matchDropDownFormInElementID:102,matchDropDownDisplayInElementID:103,matchDropDownNInElementName:104,
matchDropDownFormNInElementName:105,matchDropDownDisplayNInElementName:106,matchDropDownNInElementID:107,matchDropDownFormNInElementID:108,matchDropDownDisplayNInElementID:109,matchDropDownLTElementName:110,matchDropDownFormLTElementName:111,matchDropDownDisplayLTElementName:112,matchDropDownLTElementID:113,matchDropDownFormLTElementID:114,matchDropDownDisplayLTElementID:115,matchDropDownLTEQElementName:116,matchDropDownFormLTEQElementName:117,matchDropDownDisplayLTEQElementName:118,matchDropDownLTEQElementID:119,
matchDropDownFormLTEQElementID:120,matchDropDownDisplayLTEQElementID:121,matchDropDownGTElementName:122,matchDropDownFormGTElementName:123,matchDropDownDisplayGTElementName:124,matchDropDownGTElementID:125,matchDropDownFormGTElementID:126,matchDropDownDisplayGTElementID:127,matchDropDownGTEQElementName:128,matchDropDownFormGTEQElementName:129,matchDropDownDisplayGTEQElementName:130,matchDropDownGTEQElementID:131,matchDropDownFormGTEQElementID:132,matchDropDownDisplayGTEQElementID:133,matchDropDownRegElementName:134,
matchDropDownFormRegElementName:135,matchDropDownDisplayRegElementName:136,matchDropDownRegElementID:137,matchDropDownFormRegElementID:138,matchDropDownDisplayRegElementID:139,matchChoiceCheckedElementName:140,matchChoiceCheckedElementID:141,matchChoiceNCheckedElementName:142,matchChoiceNCheckedElementID:143,currentDateOffsetPlusGTVar:144,currentDateOffsetPlusLTVar:145,currentDateOffsetMinusGTVar:146,currentDateOffsetMinusLTVar:147,runJavaScript:148,timeOnPageEQ:149,timeOnPageNEQ:150,timeOnPageGT:151,
timeOnPageLT:152,timeOnPageGTEQ:153,timeOnPageLTEQ:154,cookieIsEnabled:155,cookieNameEQName:156,cookieNameNEQName:157,cookieNameContainsName:158,cookieNameNContainsName:159,cookieNameRegName:160,cookieNameInName:161,cookieNameNInName:162,cookieTextEQName:163,cookieTextNEQName:164,cookieTextContainsName:165,cookieTextNContainsName:166,cookieTextRegName:167,cookieTextInName:168,cookieTextNInName:169,cookieNumEQName:170,cookieNumNEQName:171,cookieNumGTName:172,cookieNumGTEQName:173,cookieNumLTName:174,
cookieNumLTEQName:175,cookieNumRegName:176,mouseClickOnID:177,mouseClickOnName:178,mouseClickOnButtonText:179,mouseClickOnSourceUrl:180,mouseClickOnAltText:181,mouseClickOnUrl:182,mouseClickOnTitleText:183,mouseMoveOutOfZone:184,mouseMoveAnywhere:185,timeout:186,maxInvitesPerVisitor:187,livehelpLaunched:188,custom:189};return{runConditions:function(c,e){if(!ba(c))return 0;e||(e={});var g={finalResult:0,groupResult:[]},f,l=c.conditions||[],n=c.operator||"and";if(!l.length)return 1;c=0;for(f=l.length;c<
f;c++)u(l[c].name)||(l[c].name=189),g.groupResult[c]=l[c].name+"@x";try{for(c=0,f=l.length;c<f;c++){var h=0,m=l[c];var v=m.name;u(m.result)?h=m.result:(0==z(v)&&(v=d[v],u(v)||(k("ERROR: no condition definition found for "+m.name),v=-1)),m.track&&q(m.track.args,function(a,b){m.args[a]=b}),h=0<=v&&a[v]?b(m.args,e,a[v],m.name):0);""===h&&k("Condition "+m.name+" failed - treated as false");g.groupResult[c]=v+"@"+(""===h?"!":Va(h));g.finalResult=h||0;if("and"===n&&!h||"or"===n&&h)return g}}catch(x){x.message+=
" ["+v+"/"+c+"]",Q(x,"condition",3,e,e&&e.exp),g.finalResult=0}return g}}}(),za,ob,A,B,P,fc,gc,xb="",T="",N={rules:[]},Aa=function(a){a&&(a=a.replace(/_[^_]*$/,""));A=a;p.CFG.expid=a},la=function(a){r.has(nb)&&(a=0);B=a;p.CFG.uoid=a;p.CFG.eeid=a;H&&(H.eeid=a);ya&&$b()},kc=location.href,G,sa,yb,lc=function(){kc!=location.href&&zb();yb=setTimeout(lc,300)},Ab=1,zb=function(){kc=location.href;ub();ya?(p.rules.page.stopProcessing=1,ra.reset(),Bb(),q(ab,function(a,b){bb(b[0],b[1],b[2],b[3])}),ab=[],p.pagepeek=
N={rules:[]},t.E={},t.B={},t.W=[],D(window._vsq)&&(_vsq=[]),Fa=da=X=Y=Qa=Pa=n,ob=ya=0,Ab&&Oa()):(Bb(),Ab&&oa())},Bb=function(){var a=p.rules;q(a.faders||{},function(a,d){q(d||[],function(a,b){clearTimeout(b)})});a.faders={};a.retryActions=[];a.retryGoals=[];a.retryCount=0;a.retryTimer&&clearTimeout(a.retryTimer);a.ruleLog=[];a.eventLog=[];a.ruledata=[];a.rulehash=Za={};a.page={startedAt:+new Date,tracker:{s:0,mouse:{type:"mousemove",state:0,x:0,y:0}},customVars:{},serverDelta:0};p.rules=a;window.eeExp&&
eeExp.start()},vb=function(a,b){var d=p.rules,c=d.maxEventLog;d=d.eventLog;var e=+new Date;c&&(0<c&&d.length>=c&&d.shift(),d.push({ts:ta(e),browserTime:e,event:a,data:b||{}}));t.occur(a,b)},pb=function(a){a=window.eStara_fsguid||mc("fs_nocache_guid")||a&&L()&&L().slice(0,50)||n;B&&(window.eStara_fsguid=a);return a},yc=function(){k("noNothing called with",arguments)},y=function(a,b){var d=p.CFG[a];a=F.CFG[a];return u(d)?d:u(a)?a:b},na=function(){return"s"==y("-eeFlag")||V},Gb=function(a){var b=location.protocol;
return na()&&!a?"https:":/file:/i.test(b)?"http:":b},Cc=function(a){var b=fa("body")||fa("html")||fa("head");b?b.appendChild(a):k("error adding to the body - no body, html or head found")},nc=function(a){return M(a)||Jb&&!!a&&!u(a.toString)&&/^\s*\bfunction\b/.test(a)},ta=function(a){return(+a||+new Date)+p.rules.page.serverDelta},u=function(a){return a!==n},Wa=function(a,b){var d=[],c=[].slice.call(arguments,1);q(a,function(a,g){c[0]=g;d[a]=b.apply(null,c)});return d},pa=function(a,b){for(var d=
[].slice.call(arguments,1),c=0,e=a.length;c<e;c++)if(d[0]=a[c],b.apply(null,d))return!0;return!1},Ta=function(a,b,d){d=d?"id":"name";a=gb(a,"*["+d+"]",d,{"case":1});return b?a[0]:a},fa=function(a){return(xa(a)||[])[0]},Pb=function(a){var b=fa("head")||fa("body")||fa("html");b?b.appendChild(a):k("error adding to the head - no head, body or html found")},U=function(a,b){var d="",c="";if(6==z(a))return a;b||(b={});a=a.replace(/^\|/,"");if(a.match("^/")){var e=a.lastIndexOf("/")||a.length;c=S(a.slice(e));
a=a.substr(1,e-1)}if(0===b["case"]||/i/.test(c))d="i";if(b.multi||/m/.test(c))d+="m";if(b.global||/g/.test(c))d+="g";return RegExp(a,d)},mc=function(a){if(0==z(a)){a=J(a);var b=r.get(a);return b?decodeURIComponent(b):r.has(a)?"":n}},Dc=function(a){var b=[];if(6==z(a)){var d=r.match(a)||{};q(d,function(a,e){d.hasOwnProperty(a)&&b.push(a)})}return b},Z=function(a,b,d){var c=window,e,g=/'|"/,f=[],l,k,h,m,v,x,w=0,p=function(a,b){return b?a:"null"===a?null:isNaN(+a)?window[a]:+a},C=[],t=document,r=0,y=
"="==b,z=/[\\[().,"' ]|\]/g;a=u(a)?J(a+"").replace(/^window\./,"").replace(/;*$/,""):"";if(""!=a){for("()"==b&&/[^)]$/.test(a)&&(a+=b);z.exec(a);)b=z.lastIndex-1,b>r&&C.push(a.slice(r,b)),C.push(a.charAt(b)),r=b+1;r<a.length&&C.push(a.slice(r));a=C[0];var I=C.length-1;if("eval"==a)w=1;else if(0==I&&y)c[a]=d;else return c[a]&&(/\[native code\]/.test(c[a])&&(t=c),"console"==a&&c.console&&(t=console)),q(C,function(a,b){if(c&&!w){if(v)e=u(e)?e+b:b,v=0;else if("\\"==b)v=1;else if(g.test(b)){x=0;if(m){b==
m?(h&&(f.push(p(e,m)),e=n),m=0):e=u(e)?e+b:b;return}m=b}else m?e=u(e)?e+b:b:"."==b?l=1:"["==b?k=1:"("==b?h=1:","==b?(x&&f.push(n),x=1):a||(c=c[b]);!a||m||~"[(.,\"' \\".indexOf(b)||("]"==b?(a==I&&y?c[e]=d:c=c[e],k=0,e=n):")"==b?((u(e)||x)&&f.push(p(e,m)),nc(c)?(c=c.apply?c.apply(t,f):Function.prototype.apply.apply(c,[t,f]),t=document):w=1,f=[],x=h=0):l?(a==I&&y?c[b]=d:c=c[b],l=0):k?e=p(b,m):h&&(f.push(p(b,m)),x=0))}}),w?n:c}},Cb=function(a){a=a.replace(/^ *body *>? */i,"");var b=document,d=b.body,
c=/^([^:]+):eq\((\d*)\)/i,e=J(a).split(">"),g,f;a&&q(e,function(a,e){e=J(e);if(!a&&e.match(/^#/))d=b.getElementById(e.slice(1));else{if(g=e.match(c))e=g[1];f=[];d&&(q(d.children,function(a,b){b&&S(b.tagName||"")==S(e)&&f.push(b)}),d=g?f[W(g[2])||0]:f)}});return d?[].concat(d):[]},Ca=function(a){var b=a.select,d="i"==a.s?"id":"name";return"c"==a.s?Cb(b)[0]:(a=gb(a.regex?U(b,a):b,"*["+d+"]",d,a))&&0<=a.length?a[0]:a},Ac=function(a,b,d,c,e,g){g=d.select||"";var f=d.value,l=function(a,b){b||(b="");if(D(a))return a.length?
Wa(a,l,b):void 0;if("c"==b)var c="radio"==a.type||"checkbox"==a.type?a.checked:null;else if(/[ifd]/.test(b)){if("select-one"!=a.type)return;c=a.selectedIndex;if(~c&&"i"!=b)return"f"==b?a[c].value:a[c].text}else{if(0==z(a.value))return a.value;if(0==z(a.innerHTML))return a.innerHTML}return c},k=function(a,b,c,d){if(b||!c){if(D(a))return Wa(a,k,b,c,d);0!=z(a)&&(a=aa(a));b&&(a=J(a));"r"==d||c||(a=S(a))}return a};if("t"==a)return+new Date-p.rules.page.startedAt;if("r"==a)return document.body;if("a"==
a)return(da||{})[g];if("N"==a){if("A"==e){var h=r.has(ma);return f?h:!h}"r"!=c&&(d["case"]=d["case"]||0);if("="==c||"!"==c)return!!r.has(U("^"+f+"$",d));h=Dc("in"==c?/^/:U(f,d));h=k(h,d.trim,d["case"],c);return"in"==c?h:"r"==c?0<h.length:h.join()}if("V"==a)return h=mc(g),b?Ya(h,b):"r"==c||d["case"]?h:S(h);if("I"==a)return(h=p.rules.page.tracker[d.viname])?!!h.state:n;if("L"==a)return"l"==e?Ec(g):Db(d);if("v"==a)h=Z(g),M(h)&&(h=h());else{if("p"==a)h=document.body;else if(/[inc]/.test(a)){h="c"==a?
Cb(g)[0]:Ta(g,0,"i"==a);if(!h)return;1==h.length&&(h=h[0])}if(null==h)return null;h=l(h,e)}if(null!=h)return h=k(h,d.trim,d["case"],c),z(h)!=b&&(h=Ya(h,b)),h},Ya=function(a,b){return D(a)?Wa(a,Ya,b):1==b?Va(a):2==b?Ea(a):3==b?oc(a):aa(a)},ia=function(a,b,d,c){null==a&&"~"==d&&(a="");if(D(a)&&"in"!=d)return a=pa(a,ia,b,d||"="),c?!a:a;if(/in/.test(d)&&!D(b))return!1;switch(d){case "!":return!a;case "=":a=a===b;break;case "<":return a<b;case "<=":return a<=b;case ">":return a>b;case ">=":return a>=b;
case "r":return b?b.test(a):!1;case "~":a=!!~a.indexOf(b);break;case "in":a=jb(a,b);break;case "bt":a=a>=b[0]&&a<=b[1];break;case "pin":a=pc(b,a);break;default:return!1}return c?!a:a},jc=function(a,b,d,c){if(a){var e=a.childNodes.length,g=0,f;if(e)for(f=a.childNodes[g];f;){if(3==f.nodeType&&f.parentNode&&!f.parentNode.tagName.match(/^script$/i)){var l=f.nodeValue;if("r"==d){if(pa(b,function(a){return a.test(l)},l))return!0}else if(c["case"]||(l=S(l)),D(b)){if(pc(b,l))return!0}else if(l.match(b))return!0}if(jc(f,
b,d,c))return!0;g++;f=g<e?a.childNodes[g]:null}}return!1},jb=function(a,b){return D(b)?D(a)?pa(a,jb,b):pa(b,function(b){return a===b},a):!1},pc=function(a,b){0!=z(b)&&(b=aa(b));return null==b?!1:pa(a,function(a){return b.match(a)},b)},S=function(a){0!=z(a)&&(a=aa(a));if(null!=a)return a.toLowerCase()},Fc={String:0,Number:1,Date:2,Boolean:3,Function:4,Object:5,RegExp:6,HTMLDocument:7,HTMLCollection:8,NodeList:9},z=function(a){a=db.call(a).slice(8,-1);var b=Fc[a];return u(b)?b:/Element/.test(a)?10:
n},ba=function(a){return"object"==typeof a},W=function(a){return parseInt(a,10)||0},Xa=function(a){return 2==z(a)&&isFinite(+a)},Ea=function(a){var b=z(a);if(0==b)if(a.match(/^\d+$/))a=new Date(+a);else{a=a.match(/^(\d{1,4})\D(\d\d?)\D(\d\d?)$/);if(!a)return null;b=+a[3];var d=+a[2]-1;a=+a[1];100>a&&(a+=70>a?2E3:1900);a=new Date(a,d,b);if(a.getDate()!=b)return null}else if(1==b)a=new Date(W(a));else{if(4==b)return Ea(a());if(2!=b)return null}if(!Xa(a))return null;b=a.getDate();d=a.getMonth()+1;return a.getFullYear()+
"-"+(10>d?"0"+d:d)+"-"+(10>b?"0"+b:b)},Va=function(a){if(null!=a){switch(z(a)){case 0:a=parseFloat(a);break;case 2:return Xa(a)?+a:null;case 3:return+a;case 4:return Va(a())}return isNaN(a)?null:a}},aa=function(a){if(null!=a){switch(z(a)){case 0:return a;case 1:return isNaN(a)?null:a+"";case 2:return Ea(a);case 3:return a+"";case 4:return aa(a());case 7:return a.innerHTML;case 8:case 9:return a.length?aa(a[0]):null;case 10:case 5:return u(a.value)?a.value:a.length?aa(a[0]):u(a.innerHTML)?a.innerHTML:
null}return u(a.value)?a.value:u(a.toString)?a.toString():null}},oc=function(a){if(null!=a){var b=z(a);return 0==b?"1"===a||/^t(rue)?$/i.test(a):1==b?!isNaN(a)&&0<a:2==b?Xa(a):3==b?a.valueOf():4==b?oc(a()):!!a}},ea=function(a,b,d){b=aa(b);if(null!=b){a.trim&&(b=J(b));a.rnvalue&&Ua("customData",{name:a.rnvalue,value:b,ruleid:d?d.id:""});a=a.value;if(0!=z(a)||!/^(total(size|type)?|[fl]name|phone|email)$/.test(a)){a=W(a);if(1>a)return;a="var"+a}p.rules.page.customVars[a]=b;d&&d.exp||/^total/.test(a)||
Z("eStara_"+a,"=",b)}},ic=function(a,b){u(b)||(b=location.href);a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(b);return u(a)&&null!==a?decodeURIComponent(a[1].replace(/\+/g," ")):null},Gc=function(a,b){a=a[b.type]||[];var d=0;if(!u(b.timeframe))return a.length;q(a,function(a,e){ia(e,b.boundary,">")&&++d});return d},Ec=function(a){var b=p.rules.page,d=0;"any-call"!=a&&(d+=(b.chats||0)+(b.ischats||0));"any-chat"!=a&&(d+=b.calls||0);return!!d},Hc=function(a){var b=a.type;var d=a.select,c="id name value src alt href title".split(" ")[b];
if(7==b)return Cb(d);0==b&&(d=d.slice(1));1==b&&(d=d.slice(7,-1));b=2==b?"input[type=button],input[type=submit],input[type=reset]":"* *  img img a a".split(" ")[b]+"["+c+"]";a.compare=a.compare||"r";return gb("r"==a.compare?U(d,a):d,b,c,a)},Db=function(a){var b=a.freq||0,d=a.freqOp||">",c=a.not,e=a.select+"",g=[],f=Eb.logs,l=0,k;a.boundary=ta(+new Date-(a.timeframe||0));/!/.test(d)&&(d=d.replace("!",""),c=!c);var h=/any(-ca|$)/.test(e),m=/any(-ch|$)/.test(e),v=/rn/.test(e);h||m||v?q(f,function(a,
b){k=S(b.type)||"";(m&&/chat$/.test(k)||h&&"call"==k||v&&k==e)&&g.push(a)}):g=e.split(",");q(g,function(b,c){l+=Gc(f[c]||{},a)});b=ia(l,b,d);return c?!b:b},Ic=function(a){var b={freqOp:">=",type:"offered",select:"any"};if(a){var d=a.ruleMaxInvite;-1>d&&(d=n);if(u(d)&&~d){b.freq=d;var c=Db(b)&&"hiddenRule"}!c&&u(a.siteMaxInvite)&&~d&&(b.freq=a.siteMaxInvite,c=Db(b)&&"hiddenSite")}return c},Sa=function(a){var b=p.rules.page.customVars;return u(a)?b[a]:b},R=function(a,b,d){k("log to server: "+a);d=new Ka(2==
d?sc:d?Ob:Ia,d);d.addResource(a,b);d.send(na())},Q=function(a,b,d,c,e){try{d&1&&(a.from=b,vb("eeError",{error:a,rule:c||{},exp:e})),d&2&&document&&R("error",{type:a.name||"?",message:p.REC_VERSION+"|"+a.message,from:b,ruleId:c&&c.id||0,ts:ta(),siteId:p.rules.page[e?"expSiteId":"siteId"]||0},e?2:0)}catch(g){k("ERROR when logging error:"+a.name+", message:"+a.message+(c&&c.id?", rule id:"+c.id:""))}k("ERROR: "+b+" error, name:"+a.name+", message:"+a.message+(c&&c.id?", rule id:"+c.id:""))},Xb="eeDebugKey",
Yb="eeDebugIP",Jc=function(){var a=window.eeDebugger&&window.eeDebugger.reset;a&&M(a)?a():(a=ja("css/debugger.css"),a=K.LINK({rel:"stylesheet",href:ib(a),type:"text/css"}),Pb(a),ca(ja("js/debugger.js")))},qa=function(a,b,d,c){var e=b.type,g=c.divId,f=1,k;b[e?"module":"name"]=a;b.rule=d;pb(1);3!=e&&5!=e&&(b.suppress="suppressed"==c.state?c.message:Ic(c));u(g)&&(q(D(g)?g:[g],function(a,b){(f=f&&u(b)&&!Ta(b,1,1))&&(k=K.DIV({id:b},k||""))}),f&&Cc(k));Ua(e?"synWidget":"cpWidget",b)},Ua=function(a,b){var d=
window._vsq;a&&d&&nc(d.push)&&ba(b)&&(b.ts||(b.ts=+new Date),d.push([a,b]))},Kc=function(a){this.rule=a;this.name=a.properties.name;this.id=a.properties.id;this.exp=a.exp;this.properties=a.properties||{};this.maxRunCount=a.properties.maxRunCount||0;this.conditionGroup=a.conditionGroup||{};this.conditions=this.conditionGroup.conditions||[];this.actionGroup=a.actionGroup||{};this.trueActions=this.actionGroup.trueActions||[];this.falseActions=this.actionGroup.falseActions||[];this.runCount=this.scheduled=
0;this.active=1;this.triggers=a.triggers||[];this.runUntil=u(this.properties.until)?this.properties.until:-1;this.runRule=function(a){var b=p.rules;if(!this.exp){if(G&&1!=G&&G!=location.href)return k("skipped running rule "+this.id+" for "+G+" as we are on "+location.href),0;if(b.page.stopProcessing)return this.active=0}if(this.chained)return 1;if(!this.active)return 0;this.runCount++;k("Run rule "+this.name+" id:"+this.id+", count:"+this.runCount);a=1;var d=b.conditions.runConditions(this.conditionGroup,
this),g=+new Date,f=d.finalResult,l=f?this.trueActions:this.falseActions,n=this.runUntil,h=b.maxRuleLog;b=b.ruleLog;this.lastEvaluation=!!f;this.lastEvaluationDetail=d.groupResult;wb.runActions(l,this);h&&(0<h&&b.length>=h&&b.shift(),b.push({ts:ta(g),browserTime:g,id:this.id,ran:f}));t.occur("eeRuleRan",{source:this});k("Rule "+this.id+" conditions evaluated as "+!!f);this.maxRunCount&&this.runCount>=this.maxRunCount&&(k("Rule "+this.id+" reached maxRunCount - setting inactive"),a=0);~n&&!!n==!!f&&
(k("Rule "+this.id+" set to inactive as the 'run until' check was met"),a=0);return this.active=a};var b=[];q(this.conditions,function(a,c){c.args||(c.args={});a=c.args;var d="viname-"+p.rules.page.tracker.s++;if(c.track){var g=c.track.args||(c.track.args={});"mousemove"==g.name&&(a.viname=g.set="mouse");a.viname||(a.viname=g.set=d);b.push(c)}});b.length&&(this.trackConditions=b)},Za={},$a=function(a,b){return function(){return a.apply(b,arguments)}},Lc=function(a,b,d){var c=b.args,e=c.after||0,g=
c.times||0,f=c.wait||0,k=d||0,n=0,h=0,m=function(){n++;if(g&&h>=g)k&&t.unbind(c.name,m);else if(n>e){var b=function(){a.runRule.apply(a,arguments);h++};f?setTimeout(b,f):b()}};return m},ra=function(){var a=0,b={},d={},c=[],e=function(){return{rules:{},args:{},id:0,run:function(){for(var a in this.rules)this.rules.hasOwnProperty(a)&&(this.rules[a].runRule.apply(this.rules[a],this.args[a]||[])||delete this.rules[a]);a:if(a=this.rules,ba(a)){for(b in a)if(a.hasOwnProperty(b)){var b=0;break a}b=1}else b=
0;b&&(this.remove(),this.stop())},stop:function(){},remove:function(){delete this.scheduled[this.name]}}},g=function(){var a={},b,c,d,e=[],g=function(){var a=window,b=document||{},c=b.documentElement||0;if(u(c.clientWidth)&&c.clientWidth)return c.clientWidth;if(b.body)return b.body.clientWidth;if(u(a.innerWidth))return a.innerWidth},f=function(a){var b=a.region,c=a.set,d=b.x,f=b.y,h=b.height,k=b.length;b=b.count;var l={id:"region:"+d+":"+f+":"+k+":"+h+":"+b,type:a.name,state:0,timestamp:[],count:0,
x:d,y:f,zoneY:f+h,zoneX:~k?d+k:g()-2,limit:b,set:c,fire:a.fire||c};a.wait?(l.active=0,setTimeout(function(){l.active=1},a.wait)):l.active=1;c&&(p.rules.page.tracker[c]=l);e.push(l)},h=function(){try{q(a,function(b,c){var d=Z(b),e=p.rules.page.tracker[b]||{};c!=d&&(k("Tracked variable "+b+" changed from "+c+" to "+d),a[b]=d,e.state=1,e.old=c,e.current=d,t.occur("varchanged-"+b,{name:b,oldValue:c,newValue:d,tracker:e}))})}catch(I){Q(I,"track-var",0)}},l=function(a,b){var c=u(b.type)?Hc(b):xa(b.select);
q(c,function(c,d){wa(d,b.name,function(b){a.count++;a.state=1;a.timestamp.push(+new Date);a.fire&&t.occur(a.fire,a)},b.select+"-"+c)});return c};wa(document,"mousemove",function(a){a||(a=window.event);var g=p.rules.page.tracker.mouse;g.y=d=a.clientY;g.x=c=a.clientX;g.state=1;if(b)for(a=0,g=e.length;a<g;a++){var f=e[a];f.active&&(!f.entered&&d<=f.zoneY&&c<=f.zoneX&&d>=f.y&&c>=f.x&&(k("Mouse region "+f.id+" entered, count:"+f.count),f.entered=1),f.entered&&(d>f.zoneY||c>f.zoneX||d<f.y||c<f.x)&&(k("Mouse region "+
f.id+" exited, count:"+f.count),f.entered=0,f.count++,f.timestamp.push(+new Date),f.count==f.limit&&(f.fire&&t.occur(f.fire,f),f.state=1,f.active=0)))}});return{reset:function(){a={};b=c=d=n;e=[]},addClickToEle:l,varchange:function(b,c){k("Track variable: "+b.name);var d=p.rules.page;if(!a[b.name]){try{var e=Z(b.name)}catch(Mc){Q(Mc,"track-var",3,c,c&&c.exp)}a[b.name]=e;d.tracker[b.name]={type:"varchange",name:b.name,state:0,current:e}}b.fire&&r(c,{run:"event",args:{name:"varchanged-"+b.name}});d.trackerid=
d.trackerid||setInterval(h,300)},domevent:function(a,c){if(a.fire){var d=1==a.fire?"event-"+p.rules.page.tracker.s++:a.fire;k("Track DOM event: "+d);a.fire=d;r(c,{run:"event",args:{name:d}})}"mouseout"==a.name&&(k("Track mouseout event"),f(a),b=1);if("click"==a.name){k("Setup click tracker for "+a.select);a.exp=c&&c.exp;c={type:a.name,state:0,count:0,timestamp:[]};d=p.rules;var e=d.page.tracker;c.set=a.set||"click-"+e.s++;c.fire=a.fire||c.set;c.set&&(e[c.set]=c);e=l(c,a);!a.exp||7!=a.type||e&&e.length||
d.retryGoals.push({click:c,args:a})}},inactivity:function(a,b){k("Setup inactivity tracker");var c=a.time||0,d={type:"timeout",time:c,state:0,fire:a.fire||0,set:a.set||"inactivity-"+p.rules.page.tracker.s++},e=d.set,f=e;d.fire&&(f=1==a.fire?e:d.fire,r(b,{run:"event",args:{name:f}}));p.rules.page.tracker[e]=d;b={id:0,name:e,resetTimer:function(){this.id&&(clearTimeout(this.id),this.start())},stop:function(){this.id=0;d.mouseHandler&&bb(document,"mousemove",d.mouseHandler,this.name);d.keyboardHandler&&
bb(document,"keydown",d.keyboardHandler,this.name)},start:function(){var a=this;this.id=d.state?0:setTimeout(function(){var b=p.rules.page.tracker[e]||{};b.state=1;a.stop();p.erg.occur(f,b)},c)}};a.mousereset&&(b.mouseHandler=$a(b.resetTimer,b),wa(document,"mousemove",b.mouseHandler,e));a.keyboardreset&&(b.keyboardHandler=$a(b.resetTimer,b),wa(document,"keydown",b.keyboardHandler,e));b.start()}}}(),f=function(a,b){k("Track "+b.length+" condition"+(1!=b.length&&"s")+" for "+a.id);q(b,function(b,c){(b=
g[c.type])&&b(c.args,a)})},l=function(){var a=p.rules,b=[],c;q(a.retryGoals,function(a,d){(c=g.addClickToEle(d.click,d.args))&&c.length||b.push(d)});a.retryGoals=b},r=function(f,g){k("Schedule rule "+f.id);var h=g.args||{},l=g.run,m=h.selector||h.select,n=h.interval||h.period,p=a+"-"+n;if(/after|every/.test(l)){m="after"==l?d:b;var x=m[p];x||(x=e(),x.period=n);k("Run "+l+" "+x+" (ms)");x.rules[l+(h.interval?"-"+h.interval:"")+"."+f.id]=f;x.scheduled=m;x.name=p;m[p]=x;"every"==l&&h.period&&c.push(f)}else"now"==
l?c.push(f):"domevent"==l?(k("Bind to DOM "+h.name+" event for "+m),q(xa(m),function(a,b){wa(b,h.name,h.after||h.times?Lc(f,g,!1):$a(f.runRule,f))})):"event"==l&&t.bind(h.name,$a(f.runRule,f),h.data||{})},h=function(){k("Clear timers and intervals");clearInterval(p.rules.page.trackerid);q(d,function(a,b){b.stop()});q(b,function(a,b){b.stop()});d={};b={}},m=function(){var a=y("-retryMax",120),b=p.rules;if(!a||b.retryCount<a)if(b.retryCount++,b.retryGoals.length&&l(),b.retryActions.length&&wb.retryActions(),
b.retryActions.length||b.retryGoals.length)b.retryTimer=setTimeout(m,y("-retryMS",50))};return{scheduleRule:function(a){if(!a.scheduled&&(a.scheduled=1,q(a.triggers,function(b,c){c.track?f(a,c.track):r(a,c)}),a.trackConditions)){k("Setup track conditions for rule "+a.id);var b=[];q(a.trackConditions,function(a,c){b.push(c.track)});f(a,b)}},clearAll:h,checkForRetries:m,start:function(){k("Schedule rules");q(c,function(a,b){k("Run rule "+b.id+" now");b.runRule()});c=[];q(d,function(a,b){b.id||(k("Setup timer for rules, timer period: "+
b.period),b.id=setTimeout(function(){b.run();b.remove()},b.period),b.stop=function(){clearTimeout(b.id)})});q(b,function(a,b){b.id||(k("Setup interval for rules, interval period: "+b.period),b.id=setInterval(function(){b.run()},b.period),b.stop=function(){clearInterval(b.id)})});a++},reset:function(){g.reset();a=0;c=[];h()}}}(),Y,X,da,Fa,Ma=function(){return(H=window.OracleUnifiedVisit)&&H.visitorId&&H.visitorId()||n},lb=function(){return(H=window.OracleUnifiedVisit)&&H.visitId&&H.visitId()||n},Qb=
function(a){window.$&&$.Topic&&$.Topic("experiment.rules.ran").publish({"for":a})},Nc=function(){var a=J(this.responseText),b=this.status;if(4==this.readyState&&(da={},204!=b&&404!=b||ka(),(200==b||304==b)&&a))try{a=JSON.parse(a)||{},q(a.audienceMembership||[],function(a,b){da[b]=!0}),ka()}catch(d){Q(d,"audienceMembership",2,n,1),k("  audienceMembershipRequest error: "+d.name+", message:"+d.message)}},Oc=function(){var a=new XMLHttpRequest,b=r.get("oauth_token_secret-storefrontUI"),d="/ccstore/v1/audienceMembership?filter="+
Fa;y("-audience-host")&&(d=y("-audience-host")+d);a.open("GET",d,!0);b&&(b="Bearer "+b.replace(/^"|"$/g,""),a.setRequestHeader("Authorization",b));a.setRequestHeader("Content-Type","application/json");a.onreadystatechange=Nc;a.send()},ka=function(){var a=p.rules,b=window;T=T||lb();if(!V||T)if(G&&1!=G&&G!=location.href&&(k("skipped EE rules for "+G+" as we are on "+location.href),Y=n),sa&&1!=sa&&sa!=location.href&&(k("skipped Exp rules for "+sa+" as we are on "+location.href),X=n),!(A&&!X||B&&!Y||
X&&!da)){var d=[].concat(Y||[],X||[]);q(d,function(b,d){b=new Kc(d);k("Load rule, name: ["+b.name+"], id:"+b.id);d.exp||(a.ruledata.push(b),Za[b.id]=b);ra.scheduleRule(b)});Y&&(b._vsq||(b._vsq=[]),Ua("rulesReady",{visitorId:L(),sessionId:T||xb,rn:1}));X=Y=n;ra.start();Qb(location.href);A&&ra.checkForRetries();a.page.debug&&Jc()}},dc=function(a){a=a||[];var b={},d,c;Fa=[];q(a,function(e,g){g&&(a[e].exp=1,g.conditionGroup&&q(g.conditionGroup.conditions||[],function(a,e){(d=e.args)&&"a"==d.s&&!u(e.result)&&
(c=d.select,b[c]||(b[c]=1,Fa.push(c)))}))});Fa.length?Oc():da={};X=a;tb(a,1)},tb=function(a,b){k("Initialize rule data");var d=b?sa:G;d&&1!=d&&d!=location.href?k("skipped E"+(b?"xp":"E")+" rules for "+d+" as we are on "+location.href):(b||(Y=a),Ba(L())?(Q({type:"badID",name:"visitorId",message:"invalid:"+L()},"loadRules",2),r.set(ma,"",-1)):ka())},ac=function(a){p.rules.page.expSiteId=a.id;rb(a,1)},rb=function(a,b){var d=a.spa;b?sa=d:G=d;d&&Lb("-eeSPA",1);y("-eeSPA")&&!V&&(yb=yb||setTimeout(lc,300));
1!=b&&(k("Load configuration data"),b=p.rules,d=b.page,b.maxRuleLog=a.logRules||0,b.maxEventLog=a.logEvents||0,d.siteId=a.id,d.creation=a.creation,d.serverPageStart=a.pageStart,d.serverDelta=a.pageStart-d.startedAt,k("Page loaded at:"+d.startedAt),k("Time difference between server time and browser time: "+d.serverDelta+"ms"),d.ppEnabled=N.enabled=a.ppEnabled||0,xb=a.sessionId||"",a.debug&&(d.debug=1,d.siteName=a.siteName,d.evalOrder=a.evalOrder,d.maxInvites=a.maxInvites,d.suppressInvites=a.suppressInvites,
d.publishDate=a.publishDate,d.fqdnHost=a.fqdnHost,d.port=a.port,d.resetRetailerTime=a.resetRetailerTime,d.jvmStartTime=a.jvmStartTime,d.currentPageURL=a.url,d.ipAddress=a.ipAddress,d.pageTitle=a.pageTitle,d.url=a.url,d.siteDebug=a.siteDebug,k=function(){var b=[].slice.call(arguments);Ga.length>a.logEvents&&Ga.shift();Ga.push(b);qc.apply(this,arguments)}),p.rules.page=d)},Zb=function(a){a=a||{};Eb.loadData(a.sessiondata)},qb=function(){r.set(nb,1);A&&(B=0,ka())},Eb=function(){return{loadData:function(a){k("Load invite session data");
this.logs=a||{}},logs:{},logInvite:function(a,b){var d=p.rules.page,c=a.id||a.ulbid||0,e=this.logs[c]||{type:a.type||""},g=e.type||"",f={inviteId:c,ruleId:a.ruleid,siteId:d.siteId,status:b,type:g,timeStamp:a.timestamp||d.serverPageStart+(+new Date-p.rules.page.startedAt)};a.children&&(f.children=a.children);a={estaraFsGuid:pb(),customVars:Sa()};a.invite=f;R("inviteEvent",a);"accepted"==b&&g&&(d[g+"s"]=++d[g+"s"]||1);/^offered/.test(b)&&(b="offered");e[b]||(e[b]=[]);e[b].push(ta());this.logs[c]=e}}}(),
uc=function(a){for(var b="cb"+ +new Date;p[b];)b+=0;p[b]=a;return"ATGSvcs."+b},p=window.ATGSvcs={CFG:F.CFG||{},visitorId:L,sessionId:hb,cfg:y,setCfg:Lb,setXD:mb,setUOID:la,setEEID:la,setEXPID:Aa,ee:{cfg:y,keepAlive:function(){B&&R("ping",{});A&&R("ping",{},1)},logInvite:function(a){a||(a={});var b=""+a.state,d={offer:"eeOffered",accep:"eeAccepted",decli:"eeDeclined",hidde:"eeHidden",suppr:"eeSuppressed",close:"eeClosed"}[b.substr(0,5)];d&&a.id&&a.type&&a.ruleid?(a.rule=Za[a.ruleid],a.timestamp=ta(a.timestamp),
Eb.logInvite(a,b),vb(d,a)):k("ERROR: invite not logged - state is invalid or id/ruleid/type not set, state:"+b+", id:"+a.id+",type:"+a.type)},reset:zb,stopRules:function(){Ab=0;zb()},enableLogView:function(a,b){r.set(Xb,a);r.set(Yb,b||"",b?n:-1);return"OK"}},debugLog:Ga,erg:t,dom:K,Selector:xa,start:oa,RESTRequest:Ka,util:{each:q,makeRegExp:U,getStaticURL:ja,paramToURL:function(a,b){a=a.replace(/\?$/,"");(b=Ja(b))&&(a+=(~a.indexOf("?")?"&":"?")+b);return a},debug:k,css:O,animate:Fb},loadExpRules:dc,
loadExpABTests:bc,loadExpTopics:cc,loadExpConfig:ac,visitIDsLoaded:function(){var a=Ma(),b=lb();k("Called from Unified Visit");a&&b?(mb(a),r.set(ma,a,!0),T=b,Wb(),Vb(),p.start(),ka()):k("Called from Unified Visit but no ids set.")},loadRules:tb,loadABTests:sb,loadInvites:Zb,loadConfig:rb,doNotCall:qb,eventSubscribe:cb,getCustomData:Sa,getSessionId:function(){return xb},getVisitId:function(){return T},pagepeek:N,rules:{ruleLog:[],eventLog:[],ruledata:[],rulehash:Za,page:{},analytics:zc,scheduler:ra,
conditions:Bc,actions:wb},REC_VERSION:215};Bb();K.tags("A|BR|DIV|IMG|LI|P|SCRIPT|SPAN|UL|B|LINK");F.uoid&&la(F.uoid);F.eeid&&la(F.eeid);F.expid&&Aa(F.expid);var V=!!fa("html#oracle-cc");fb?k("Gomez Browser Detected.  Skipping DOMContentLoaded Handlers."):vc();if(/[?;&]eeExpLoad=(\d+)/.test(location.search)||r.has("eeExpKey")){r.set("eeExpKey",1);try{window.self!==window.top&&(za=1)}catch(a){za=1}}}})();
